[project]
name = "merkle-priority"
description = "A Clarity smart contract suite for managing priority-based, location-aware decentralized content discovery and access"
authors = ["Anonymous Developer"]
telemetry = false
requirements = []

[contracts.priority-core]
path = "contracts/priority-core.clar"
clarity_version = "2"
epoch = 2.4

[contracts.priority-marketplace]
path = "contracts/priority-marketplace.clar"
clarity_version = "2"
epoch = 2.4

[contracts.priority-social]
path = "contracts/priority-social.clar"
clarity_version = "2"
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl]
cost_model = "docker"
estimated_liability = "small"